pipeline:
  setup::
    image: docker
    commands:
      - docker build --rm -t docker-ping-check .
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    when:
      branch: master
      event: push