pipeline:
  setup:
    image: docker
    commands:
      - docker build --rm -t docker-ping-check .
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    when:
      branch: [master, development]
      event: push
  
  check_running:
    image: docker
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    commands:
      - sleep 5
      - docker ps | grep docker-ping-check
    when:
      branch: [master, development]
      event: push
  
  docker:
    image: plugins/docker
    repo: duncan9562/docker-ping-check
    secrets: [ docker_username, docker_password ]
    auto_tag: true
    when:
      branch: master
      event: push
