pipeline:
  setup::
    image: docker
    commands:
      - docker build --rm -t docker-ping-check .
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    when:
      branch: [master, development]
      event: push
  docker:
    image: duncan9562/docker-ping-check
    secrets: [ docker_username, docker_password ]
